"""Validate bank structure, SVG safety, deterministic assets and Classic preservation."""
from pathlib import Path
import hashlib, importlib.util, json, re, shutil, tempfile
import xml.etree.ElementTree as ET
ROOT=Path(__file__).resolve().parents[1]

def digest(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def run():
    bank=json.loads((ROOT/'g57_bank.json').read_text())
    assert len(bank['sets'])==16
    ids=set(); questions=set(); diagram_refs=set(); counts={'Core':0,'Enrichment':0}
    allowed={'times','cdot','div','frac','sqrt','circ','pi','leq','geq','neq','infty','pm','rightarrow','to','square','ldots','cdots','le','ge','lt','gt','angle','triangle','equiv','text','mathrm','left','right','quad','qquad'}
    for s in bank['sets']:
        assert s['id'] not in ids;ids.add(s['id'])
        assert s['kind'] in counts and len(s['problems'])==12
        counts[s['kind']]+=len(s['problems'])
        assert len(s['lesson'])>=3
        for p in s['problems']:
            assert p['id'] not in ids;ids.add(p['id'])
            assert p['q'] not in questions;questions.add(p['q'])
            assert p['level'] in (1,2,3)
            for key in ['q','answer','hint','solution']:
                t=p[key];assert isinstance(t,str) and t.strip(),(p['id'],key)
                assert t.count('$')%2==0,(p['id'],key,'unpaired math delimiter')
                assert t.count('{')==t.count('}'),(p['id'],key,'unbalanced braces')
                assert not re.search(r'<(?:script|iframe|img)|onerror=',t,re.I)
                assert '\u2014' not in t
                for cmd in re.findall(r'\\([A-Za-z]+)',t):assert cmd in allowed,(p['id'],cmd)
            if p.get('diagram'):
                diagram_refs.add(p['diagram'])
                assert p['diagram'] in bank['diagrams'] and len(p.get('imageAlt',''))>15,p['id']
        standalone=json.loads((ROOT/'sets/g57'/f'{s["id"]}.json').read_text())
        assert standalone['name']==s['name']
        for p in standalone['problems']:
            if 'image' in p:assert (ROOT/'sets/g57'/p['image']).resolve().is_file()
    assert counts=={'Core':108,'Enrichment':84}
    assert diagram_refs==set(bank['diagrams']),('unused diagrams',set(bank['diagrams'])-diagram_refs)
    assert len(diagram_refs)==25
    for name,svg in bank['diagrams'].items():
        node=ET.fromstring(svg)
        assert node.tag.endswith('svg') and 'viewBox' in node.attrib
        assert node.find('{http://www.w3.org/2000/svg}title') is not None
        assert not re.search(r'<(?:script|foreignObject|image)|(?:onload|onerror)\s*=|https?://(?!www.w3.org)',svg,re.I),name
        assert (ROOT/'assets/diagrams'/f'{name}.svg').read_text()==svg
    for manifest_path in [ROOT/'question_bank.json',ROOT/'sets/g57/question_bank.json']:
        m=json.loads(manifest_path.read_text())
        for name in m['sets']:
            f=(manifest_path.parent/name).resolve();assert f.is_file(),name
            legacy=json.loads(f.read_text());assert isinstance(legacy['problems'],list) and legacy['problems']
    expected=json.loads((ROOT/'tests/classic_manifest.json').read_text())
    for path,h in expected.items():assert digest(ROOT/path)==h,f'Preserved source changed: {path}'
    # Rebuild into an isolated directory and compare the exact generated bytes.
    spec=importlib.util.spec_from_file_location('builder',ROOT/'tools/build_bank.py');mod=importlib.util.module_from_spec(spec);spec.loader.exec_module(mod)
    with tempfile.TemporaryDirectory() as d:
        temp=Path(d);(temp/'content').mkdir();shutil.copy(ROOT/'content/sets.txt',temp/'content/sets.txt');mod.ROOT=temp;mod.build()
        for generated in temp.rglob('*'):
            if generated.is_file() and generated.parent.name!='content':
                rel=generated.relative_to(temp);assert generated.read_bytes()==(ROOT/rel).read_bytes(),f'Stale generated file: {rel}'
    print(f'Validated {len(questions)} unique questions, 25 SVGs, reproducible build, and {len(expected)} preserved original files.')
if __name__=='__main__':run()
